### ISSUE TITLE
Document current status of upstream patch and possible alternatives

### ISSUE THREAD

**Issue by evilaliv3** [nstommel/broadwell-gfx-kernel-patch#2] opened 2017-02-16 14:51 UTC
Hi @nstommel can i please ask you to document the current status of the upstram patching and the releveant discussions on the topic?

Is there any alternative to install a custom kernel that could at least reduce the issues?

Have you tried so get your patchset official in debian/ubuntu so that other users will benefit of them without requireing to install a not signed package?

thank you so much!

**Comment by veaprapre** [comment] 2017-02-20 23:40
If you read the whole [discussion](https://bugs.freedesktop.org/show_bug.cgi?id=97918) then you see that Nick only reverts upstream patch which was fixing some regressions. Unfortunately earlier regression trumps later one so it's unlikely that this patch will be reverted upstream.

The problem is that some devices need one config and some need another config and upstream don't know how to assign wanted configs to relevant devices automatically. Whatever config they choose some devices will be broken. Finally they decided to disable psr by default since 4.9 kernel

Considering above I don't think ubuntu or debian maintainers will fix this themselves.

There is also whitelist device option but as most notebook models have unique firmware, all of them have to be added one by one.

BTW: If you don't want to install unsigned kernel you can compile it yourself with provided patches.

**Comment by evilaliv3** [comment] 2017-02-21 08:53
Thank you so much @veaprapre 

what i do not understand is why i'm having the same issue solved the kernels provided here on ubuntu xenial that is running 4.4.0.

If i'm not wrong you are declaring that the issue exists only starting from 4.7.4.

What am i not understanding?

**Comment by veaprapre** [comment] 2017-02-21 10:31
I don't know if I understand it correctly - You have this issue in 4.4.x?

As I remember Panel Self Refresh (PSR) for i915 intel driver was supported (enabled by default) only since 4.6.0 kernel and this issue also occurred then. It was fixed in kernel from 4.7.0 to 4.7.4. Since 4.7.5 and later it appears again. Since 4.9.x (don't remember exactly version) PSR is unsupported and disabled by default again.

I've never used PSR before 4.6.0 kernel because it was unsupported but if you force enable it there is a chance it's bugged too.

**Comment by evilaliv3** [comment] 2017-02-21 11:22
I see, i maybe totally wong so.

When i tried the kernels provided here time ago all was fine, but maybe the issue i'm facing on Ubuntu Xenial that visually is the same is not related to the same kernel problem.

What i see in dmesg logs is the following:
```
[  410.580799] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 60Hz
[  421.205505] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 40Hz
[  421.480879] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 60Hz
[  428.289331] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 40Hz
[  428.630893] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 60Hz
[  431.389343] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 40Hz
[  432.155824] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 60Hz
[  433.329304] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 40Hz
[  442.205839] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 60Hz
[  443.381063] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 40Hz
[  445.947769] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 60Hz
[  464.340726] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 40Hz
[  464.965411] [drm:intel_dp_set_drrs_state] eDP Refresh Rate set to : 60Hz
```

probably this is the reason of the human noticeble problem.

**Comment by veaprapre** [comment] 2017-02-21 12:40
Try command:
`sudo cat /sys/module/i915/parameters/enable_psr`
If the result is `0` it means you have PSR disabled and your issue is unrelated to this one.
If the result is `1` it means you have PSR enabled, then add:
`i915.enable_psr=0` to your kernel commandline in grub or whatever you use to boot system. If the issue is gone then it's same issue as here.

I think that logs you provided are normal and unrelated.

**Closed** 2017-06-22 02:45 UTC
